# Generated by Django 5.2 on 2025-04-17 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcement', '0001_initial'),
        ('competition_space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='competition_space.competitionspace'),
        ),
        migrations.AddField(
            model_name='announcementreadrecord',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.announcement'),
        ),
        migrations.AddField(
            model_name='announcementreadrecord',
            name='space_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to='competition_space.spaceuser'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementreadrecord',
            unique_together={('space_user', 'announcement')},
        ),
    ]
