# Generated by Django 5.2 on 2025-04-17 00:37

import competition_space.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_user_gender_notify'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to=competition_space.models.poster_path)),
                ('category', models.CharField(choices=[('subject', '学科竞赛'), ('innovation', '创新创业'), ('entertainment', '文娱竞赛'), ('others', '其它')], max_length=50)),
                ('level', models.CharField(choices=[('school', '校级'), ('province', '省级'), ('national', '国家级')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_competitions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
            ],
            options={
                'db_table': 'competition_space',
            },
        ),
        migrations.CreateModel(
            name='SpaceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realName', models.CharField(blank=True, max_length=30, null=True)),
                ('studentId', models.CharField(blank=True, max_length=30, null=True)),
                ('collegeName', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10)),
                ('phoneNumber', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='手机号码必须是 11 位数字', regex='^\\d{11}$')])),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('is_captain', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space', to='competition_space.competitionspace')),
            ],
            options={
                'db_table': 'space_user',
            },
        ),
    ]
