# Generated by Django 5.2 on 2025-04-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceMembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realName', models.CharField(max_length=30)),
                ('studentId', models.CharField(max_length=30)),
                ('collegeName', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '通过'), ('rejected', '驳回')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('need_to_notify', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'space_membership_request',
            },
        ),
        migrations.CreateModel(
            name='TeamMembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '接受'), ('rejected', '拒绝')], default='pending', max_length=20)),
                ('request_detail', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('need_to_notify', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'team_membership_request',
            },
        ),
    ]
