# Generated by Django 5.2 on 2025-04-17 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('competition_space', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spacemembershiprequest',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='competition_space.competitionspace'),
        ),
        migrations.AddField(
            model_name='spacemembershiprequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammembershiprequest',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='teams.team'),
        ),
        migrations.AddField(
            model_name='teammembershiprequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
