# Generated by Django 5.2 on 2025-04-14 20:42

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='手机号码必须是 11 位数字', regex='^\\d{11}$')])),
                ('username', models.CharField(blank=True, max_length=25, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=accounts.models.avatar_path)),
                ('role', models.CharField(choices=[('platform_admin', '平台管理员'), ('school_super_admin', '学校超级管理员'), ('competition_admin', '竞赛负责人'), ('student', '普通学生')], default='student', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
