# Generated by Django 5.2 on 2025-04-14 16:04

from django.db import migrations

def create_default_school(apps, schema_editor):
    School = apps.get_model('accounts', 'School')
    if not School.objects.exists():
        School.objects.create(name="Default School")

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_set_initial_id'),
    ]

    operations = [
        migrations.RunPython(create_default_school),
    ]
